### ISSUE TITLE
[NSFW] Checking loop

### ISSUE THREAD

**Issue by Sinnoma** [PredaaA/predacogs#18]
I've noticed an error using `await ctx.bot.send_help_for()`

When we're using this method, and when we ask the help of Nsfw cog, there will be a loop saying : 🔒 You can't use this command in a non-NSFW channel !

To reproduce that error, create a cog that will use `await ctx.bot.send_help_for()`, like a custom help command, and use `[p]yourCommand Nsfw`

**Comment by Sinnoma** [comment]
If it can help you
Unloading the cog that asked the help_for, spam will stop and return a correct help (Without NSFW commands)

**Comment by Flame442** [comment]
This is happening because that message is sent as a part of the checks for the commands in that cog. `bot.send_help_for` runs these checks (in the given context) to determine if a command should be shown or not (does the user have perms, is the command enabled, etc). As a result, the failure message in the check is sent for *every* command (with that check), causing the spam you noticed.
